// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stringsvc.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	stringsvc.proto

It has these top-level messages:
	UppercaseRequest
	UppercaseReply
	CountRequest
	CountReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UppercaseRequest struct {
	A string `protobuf:"bytes,1,opt,name=a" json:"a,omitempty"`
}

func (m *UppercaseRequest) Reset()                    { *m = UppercaseRequest{} }
func (m *UppercaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UppercaseRequest) ProtoMessage()               {}
func (*UppercaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UppercaseRequest) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

type UppercaseReply struct {
	Str string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *UppercaseReply) Reset()                    { *m = UppercaseReply{} }
func (m *UppercaseReply) String() string            { return proto.CompactTextString(m) }
func (*UppercaseReply) ProtoMessage()               {}
func (*UppercaseReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UppercaseReply) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *UppercaseReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type CountRequest struct {
	A string `protobuf:"bytes,1,opt,name=a" json:"a,omitempty"`
}

func (m *CountRequest) Reset()                    { *m = CountRequest{} }
func (m *CountRequest) String() string            { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()               {}
func (*CountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CountRequest) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

type CountReply struct {
	Count string `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *CountReply) Reset()                    { *m = CountReply{} }
func (m *CountReply) String() string            { return proto.CompactTextString(m) }
func (*CountReply) ProtoMessage()               {}
func (*CountReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CountReply) GetCount() string {
	if m != nil {
		return m.Count
	}
	return ""
}

func (m *CountReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*UppercaseRequest)(nil), "pb.UppercaseRequest")
	proto.RegisterType((*UppercaseReply)(nil), "pb.UppercaseReply")
	proto.RegisterType((*CountRequest)(nil), "pb.CountRequest")
	proto.RegisterType((*CountReply)(nil), "pb.CountReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Add service

type AddClient interface {
	Uppercase(ctx context.Context, in *UppercaseRequest, opts ...grpc.CallOption) (*UppercaseReply, error)
	Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountReply, error)
}

type addClient struct {
	cc *grpc.ClientConn
}

func NewAddClient(cc *grpc.ClientConn) AddClient {
	return &addClient{cc}
}

func (c *addClient) Uppercase(ctx context.Context, in *UppercaseRequest, opts ...grpc.CallOption) (*UppercaseReply, error) {
	out := new(UppercaseReply)
	err := grpc.Invoke(ctx, "/pb.Add/Uppercase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addClient) Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountReply, error) {
	out := new(CountReply)
	err := grpc.Invoke(ctx, "/pb.Add/Count", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Add service

type AddServer interface {
	Uppercase(context.Context, *UppercaseRequest) (*UppercaseReply, error)
	Count(context.Context, *CountRequest) (*CountReply, error)
}

func RegisterAddServer(s *grpc.Server, srv AddServer) {
	s.RegisterService(&_Add_serviceDesc, srv)
}

func _Add_Uppercase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UppercaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Uppercase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/Uppercase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Uppercase(ctx, req.(*UppercaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Add_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Count(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Add_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Add",
	HandlerType: (*AddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Uppercase",
			Handler:    _Add_Uppercase_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Add_Count_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stringsvc.proto",
}

func init() { proto.RegisterFile("stringsvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0x2f, 0x2e, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x52, 0xe0, 0x12, 0x08, 0x2d, 0x28, 0x48, 0x2d, 0x4a, 0x4e, 0x2c, 0x4e, 0x0d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe1, 0x62, 0x4c, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62,
	0x4c, 0x54, 0x32, 0xe1, 0xe2, 0x43, 0x52, 0x51, 0x90, 0x53, 0x29, 0x24, 0xc0, 0xc5, 0x5c, 0x5c,
	0x52, 0x04, 0x55, 0x01, 0x62, 0x82, 0x44, 0x52, 0x8b, 0x8a, 0x24, 0x98, 0x20, 0x22, 0xa9, 0x45,
	0x45, 0x4a, 0x32, 0x5c, 0x3c, 0xce, 0xf9, 0xa5, 0x79, 0x25, 0xb8, 0xcc, 0xe4, 0x82, 0xca, 0x82,
	0xcc, 0x13, 0xe1, 0x62, 0x4d, 0x06, 0xf1, 0xa0, 0xf2, 0x10, 0x0e, 0xa6, 0x99, 0x46, 0xd9, 0x5c,
	0xcc, 0x8e, 0x29, 0x29, 0x42, 0xe6, 0x5c, 0x9c, 0x70, 0x07, 0x09, 0x89, 0xe8, 0x15, 0x24, 0xe9,
	0xa1, 0xfb, 0x40, 0x4a, 0x08, 0x4d, 0xb4, 0x20, 0xa7, 0x52, 0x89, 0x41, 0x48, 0x9b, 0x8b, 0xd5,
	0x19, 0x62, 0x34, 0x48, 0x1a, 0xd9, 0x79, 0x52, 0x7c, 0x48, 0x22, 0x60, 0xc5, 0x49, 0x6c, 0xe0,
	0x30, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x91, 0xcf, 0x10, 0x36, 0x01, 0x00, 0x00,
}
